// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxuHdiRubAWMZS3jTSn_d9GIGsDYg5xU',
    appId: '1:352855004713:web:55d27b5faf2f6fc7da6e38',
    messagingSenderId: '352855004713',
    projectId: 'app-529f5',
    authDomain: 'app-529f5.firebaseapp.com',
    storageBucket: 'app-529f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxuHdiRubAWMZS3jTSn_d9GIGsDYg5xU',
    appId: '1:352855004713:android:f5493faeb8b58a29da6e38',
    messagingSenderId: '352855004713',
    projectId: 'app-529f5',
    storageBucket: 'app-529f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yyWsffZDFcgMAr1lx-aPN5rGph0ziB4',
    appId: '1:352855004713:ios:ffee94c613faafc3da6e38',
    messagingSenderId: '352855004713',
    projectId: 'app-529f5',
    storageBucket: 'app-529f5.firebasestorage.app',
    iosBundleId: 'com.example.newIlkProjem',
  );

} 